# Generated by Django 2.2.4 on 2019-10-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('driver', models.CharField(max_length=30)),
                ('conductor', models.CharField(max_length=30)),
                ('conductor_name', models.CharField(max_length=30)),
                ('driver_name', models.CharField(max_length=30)),
            ],
        ),
    ]
