# Generated by Django 2.2.6 on 2019-12-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_assign_bus_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='code',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
