# Generated by Django 2.2.4 on 2019-10-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studs',
            fields=[
                ('usn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=50)),
                ('mother', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('college', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=50)),
                ('destiantion', models.CharField(max_length=50)),
                ('changeover', models.CharField(max_length=50)),
                ('ackno', models.CharField(max_length=10)),
                ('status', models.CharField(default='not approved', max_length=15)),
            ],
        ),
    ]
