# Generated by Django 2.2.4 on 2019-10-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studs',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
