# Generated by Django 2.2.4 on 2019-10-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20191005_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studs',
            name='ackno',
            field=models.CharField(default='nill', max_length=10),
        ),
    ]
