# Generated by Django 2.2.4 on 2019-10-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20191007_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='studs',
            name='statusc',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
