# Generated by Django 2.2.4 on 2019-10-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(max_length=15)),
                ('bus_stand_name', models.CharField(max_length=30)),
                ('bus_service_years', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('changeover', models.CharField(max_length=30)),
            ],
        ),
    ]
